version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - app_db
  app_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crud-users
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
volumes:
  pgdata: